cao =    Author.create(first_name: 'Cao',        last_name: 'Xueqin',      nationality: 'Chinese',                   birth_year: 1715)
jk =     Author.create(first_name: 'J.K.',       last_name: 'Rowling',     nationality: 'United Kingdom',            birth_year: 1965)
james =  Author.create(first_name: 'James',      last_name: 'Baldwin',     nationality: 'United States of America',  birth_year: 1924)
jorge =  Author.create(first_name: 'Jorge Luis', last_name: 'Borges',      nationality: 'Argentina',                 birth_year: 1899)
haruki = Author.create(first_name: 'Haruki',     last_name: 'Murakami',    nationality: 'Japan',                     birth_year: 1949)
milan =  Author.create(first_name: 'Milan',      last_name: 'Kundera',     nationality: 'Czechoslovakia',            birth_year: 1929)
albert = Author.create(first_name: 'Albert',     last_name: 'Camus',       nationality: 'France',                    birth_year: 1913)
george = Author.create(first_name: 'George',     last_name: 'R.R. Martin', nationality: 'United States of America',  birth_year: 1945)

# Cao Xueqin
cao.books.create(title: 'Dream of the Red Chamber', publication_date: 1750)

# J.K. Rowling
jk.books.create(title: 'Harry Potter and the Philosophers Stone', publication_date: 1997)
jk.books.create(title: 'Harry Potter and the Chamber of Secrets', publication_date: 1998)
jk.books.create(title: 'Harry Potter and the Prisoner of Azkaban', publication_date: 1998)
jk.books.create(title: 'Harry Potter and the Goblet of Fire', publication_date: 2000)
jk.books.create(title: 'Harry Potter and the Order of the Phoenix', publication_date: 2003)
jk.books.create(title: 'Harry Potter and the Half-Blood Prince', publication_date: 2005)
jk.books.create(title: 'Harry Potter and the Deathly Hallows', publication_date: 2007)
jk.books.create(title: 'The Casual Vacancy', publication_date: 2012)

# James Baldwin
james.books.create(title: 'Go Tell It on the Mountain ', publication_date: 1953)
james.books.create(title: 'The Amen Corner ', publication_date: 1954)
james.books.create(title: 'Notes of a Native Son ', publication_date: 1955)
james.books.create(title: 'Giovannis Room ', publication_date: 1956)
james.books.create(title: 'Nobody Knows My Name: More Notes of a Native Son ', publication_date: 1961)
james.books.create(title: 'Another Country ', publication_date: 1962)
james.books.create(title: 'A Talk to Teachers ', publication_date: 1963)
james.books.create(title: 'The Fire Next Time ', publication_date: 1963)
james.books.create(title: 'Blues for Mister Charlie ', publication_date: 1964)
james.books.create(title: 'Going to Meet the Man ', publication_date: 1965)
james.books.create(title: 'Tell Me How Long the Trains Been Gone ', publication_date: 1968)
james.books.create(title: 'No Name in the Street ', publication_date: 1972)
james.books.create(title: 'If Beale Street Could Talk ', publication_date: 1974)
james.books.create(title: 'The Devil Finds Work ', publication_date: 1976)
james.books.create(title: 'Just Above My Head ', publication_date: 1979)
james.books.create(title: 'Jimmys Blues ', publication_date: 1983)
james.books.create(title: 'The Evidence of Things Not Seen ', publication_date: 1985)
james.books.create(title: 'The Price of the Ticket ', publication_date: 1985)
james.books.create(title: 'The Cross of Redemption: Uncollected Writings ', publication_date: 2010)
james.books.create(title: 'Jimmys Blues and Other Poems ', publication_date: 2014)

# Jorge Luis Borges
jorge.books.create(title: 'Fervor de Buenos Aires', publication_date: 1923)
jorge.books.create(title: 'Inquisiciones', publication_date: 1925)
jorge.books.create(title: 'Luna de Enfrente', publication_date: 1925)
jorge.books.create(title: 'El idioma de los argentinos', publication_date: 1928)
jorge.books.create(title: 'Cuaderno San Martín', publication_date: 1929)
jorge.books.create(title: 'Discusión', publication_date: 1957)
jorge.books.create(title: 'Historia de la eternidad', publication_date: 1936)
jorge.books.create(title: 'El jardín de senderos que se bifurcan', publication_date: 1941)
jorge.books.create(title: 'Seis problemas para don Isidro Parodi', publication_date: 1942)

# Haruki Murakami
haruki.books.create(title: 'Hear the Wind Sing', publication_date: 1987)
haruki.books.create(title: 'A Wild Sheep Chase', publication_date: 1989)
haruki.books.create(title: 'Norwegian Wood', publication_date: 2000)
haruki.books.create(title: 'Dance Dance Dance', publication_date: 1994)
haruki.books.create(title: 'South of the Border, West of the Sun', publication_date: 2000)
haruki.books.create(title: 'The Wind-Up Bird Chronicle', publication_date: 1997)
haruki.books.create(title: 'Sputnik Sweetheart', publication_date: 2001)
haruki.books.create(title: 'Kafka on the Shore', publication_date: 2005)
haruki.books.create(title: 'After Dark', publication_date: 2007)
haruki.books.create(title: '1Q84', publication_date: 2011)

# Milan Kundera
milan.books.create(title: 'The Joke', publication_date: 1967)
milan.books.create(title: 'The Farewell Waltz', publication_date: 1972)
milan.books.create(title: 'Life Is Elsewhere', publication_date: 1973)
milan.books.create(title: 'The Book of Laughter and Forgetting', publication_date: 1978)
milan.books.create(title: 'The Unbearable Lightness of Being', publication_date: 1984)
milan.books.create(title: 'Immortality', publication_date: 1990)
milan.books.create(title: 'Slowness', publication_date: 1995)
milan.books.create(title: 'Identity', publication_date: 1998)
milan.books.create(title: 'Ignorance', publication_date: 2000)

# Albert Camus
albert.books.create(title: 'The Stranger', publication_date: 1942)
albert.books.create(title: 'The Plague', publication_date: 1947)
albert.books.create(title: 'The Fall', publication_date: 1956)
albert.books.create(title: 'A Happy Death', publication_date: 1971)
albert.books.create(title: 'The First Man', publication_date: 1995)

# George RR Martin
george.books.create(title: 'A Game of Thrones', publication_date: 1996)
george.books.create(title: 'A Clash of Kings', publication_date: 1998)
george.books.create(title: 'A Storm of Swords', publication_date: 2000)
george.books.create(title: 'A Feast for Crows', publication_date: 2005)
george.books.create(title: 'A Dance with Dragons', publication_date: 2011)
george.books.create(title: 'I Swear the Dragons are Coming Soon', publication_date: 2014)
